version: '1.0'

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build:
    image: docker:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t registry.localhost:5000/react-article-display:latest .

      - name: Push Docker Image to Local Registry
        run: |
          docker push registry.localhost:5000/react-article-display:latest
