version: '1.0'

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    image: docker:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t your-docker-image-name:latest .
          docker push your-docker-image-name:latest